### ISSUE TITLE
allow other port than port 80

### ISSUE THREAD

**Issue by ginader** [paypal/AATT#1]
please add a param that allows starting the server on another port than 80

**Comment by mpnkhan** [comment]
Hi Dirk ,
Thanks for the filing this issue. Your contributions are most welcome :+1:

**Comment by ginader** [comment]
thanks @mpnkhan! It would be even better if that port could be a command line argument so the users of your script don't have to modify your code to use it (makes updating easier).
See here for good example code on how to achieve this: http://blog.npmjs.org/post/119377806820/making-your-command-line-tool-configurable

**Comment by vick08** [comment]
Great idea!

**Comment by mpnkhan** [comment]
This Pull request from @nikulkarni  , https://github.com/paypal/AATT/pull/4 fixes this issue . 
Thanks @nikulkarni  and Thank you @ginader
