### ISSUE TITLE
About crawl-based testing, authenticated flows, and continuous integration

### ISSUE THREAD

**Issue by softwareklinic** [paypal/AATT#10]
Can this tool also perform crawl-based accessibility analysis, analysis of authenticated flows (sign-in), and be integrated into the CI CD pipeline?

**Comment by mpnkhan** [comment]
Use other tools like nightwatch, nemo or jasmin  to write test cases, which involve login, saving session etc.  Use this tool as an api to evaluate for accessibility. 
For more info see readme: How to Use with nemo-accessibility as a plugin
