### ISSUE TITLE
Error from git -- git submodule update

### ISSUE THREAD

**Issue by RichCaloggero** [paypal/AATT#12]
When doing git submodule update, I get the following error:
...
fatal: reference is not a tree: 02ea409a140269b32d6a8c0466304cf812e5e209
Unable to checkout '02ea409a140269b32d6a8c0466304cf812e5e209' in submodule path
'src/htmlcs'
...

This occurs on both linux and windows using node 4.2.2, 

The app runs and I get the initial "express log started" message,. The html page comes up on localhost:<port>  but when I submit a url for testing, I get the "if this message appears for more than 50 seconds click here" and nothing else; the test never completes and nothing shows up in the log.

Thanx for any info you can provide.

**Comment by mpnkhan** [comment]
Yes you are correct. I tried to do the submodule update now, and none of them were checkout. 
As a workaround can you try, deleting the submodule directory in src folder and cloning htmlcodesniffer there.

$ cd src
$ rm -r htmlcs
$ git clone https://github.com/squizlabs/HTML_CodeSniffer.git htmlcs
Cloning into 'htmlcs'...
remote: Counting objects: 7296, done.
remote: Total 7296 (delta 0), reused 0 (delta 0), pack-reused 7296
Receiving objects: 100% (7296/7296), 4.83 MiB | 608.00 KiB/s, done.
Resolving deltas: 100% (3743/3743), done.
Checking connectivity... done.
$cd ..
$ sudo DEBUG=AATT* http_port=80 node app.js
Password:
  AATT:log Express started on port  +0ms 80
  AATT:log <div id="resultsWrapper" class="resultsWrapperActive"><h3>Yahoo</h3><h4>https://sg.yahoo.com/?p=us</h4>

There is a TO DO task to allow chrome/axe from UI.  So this could be bypassed.

**Comment by RichCaloggero** [comment]
Yes, this seems to work fine.

Looking at the git docs, it suggests that submodule update attempts to access a specific commit. Is it possible to simply ask for the latest available commit instead of a specific  one by id?

-- Rich
