### ISSUE TITLE
results never load

### ISSUE THREAD

**Issue by itsreallynotadam** [paypal/AATT#13]
Everything installed correctly and is running locally without issues. However I never receive a result from the web-application, only "Loading.... Please wait...." dialog.

Wasn't running into any node issues, but shut down the apache server for good measure, removed local directory, fresh clone/dependency install and re-init. results in the same outcome.

Any thoughts?
![screen shot 2016-04-05 at 12 00 59 pm](https://cloud.githubusercontent.com/assets/4728921/14288745/149d2322-fb26-11e5-8393-86ad751a15c4.png)

**Comment by mpnkhan** [comment]
Please check the contents of src/htmlcs. 
Recently found a problem with the branch of htmlcs.
If you didn't find any contents cd to that directory and  say "git checkout master"

**Comment by itsreallynotadam** [comment]
That did it. Thanks for the help!
