### ISSUE TITLE
Unable to use HTMLCS.

### ISSUE THREAD

**Issue by garry-edmonds** [paypal/AATT#14]
I am trying to use the HTMLCS option, using both the API and website, both hang when it tries to get the response from the server and no results are available.  Eventually I get a timeout error on the API.  But no reason for the hanging.  

Get this info from the webserver.

E N G I N E  undefined [ '--config=config/config.json',
  '/home/mint/aatt/src/HTMLCS_Run.js',
  'tmp/1468921496350.html',
  'WCAG2AAA',
  '1,2,3',
  'json' ]
  AATT:log sniffHTML, E N G I N E  +9m htmlcs

**Comment by mpnkhan** [comment]
Can you pull the latest? Updated htmlcs submodule. 
Also check if src/htmlcs folder has files in it?

**Comment by garry-edmonds** [comment]
I have updated HTMLCS modules and can confirm scr/htmlcs has files in it.
But now when I try and update the submodule I get the error:

fatal: reference is not a tree: f49a6c8139c626f2aa2cdcf2681f241c72820591
Unable to checkout 'f49a6c8139c626f2aa2cdcf2681f241c72820591' in submodule path 'src/htmlcs'

**Comment by mpnkhan** [comment]
Try this and let me know is this works. Will be removing htmlcs submodule soon. How about with axe or chrome engine? Does that work?

$ cd src
$ rm -r htmlcs
$ git clone https://github.com/squizlabs/HTML_CodeSniffer.git htmlcs
$cd ..
$ sudo DEBUG=AATT* http_port=80 node app.js

**Comment by garry-edmonds** [comment]
I have done the above and still have the same issue.

Both Axe and Chrome are working correctly, but with these two options I can't pass in the error level or Level and would like to return a JSON object instead.  Which is why I wanted to use the HTMLCS.

**Comment by mpnkhan** [comment]
Found the problem with latest version of htmlcs. Added it as folder. 
Could you update to latest and check if this works?
