### ISSUE TITLE
Different results from AATT web application and AATT with nemo-accessibility

### ISSUE THREAD

**Issue by palashkochar** [paypal/AATT#15]
I am trying to automate accessibility testing. I tried using AATT web application and also AATT with  nemo-accessibility but I am getting different results from both. Is it expected to get different results? If yes, can you explain why?
I saw they are hitting different api end points **/sniffUrl** and **/evaluate** but I am not able to understand why I am getting different results because both are used to test accessibility.

**Comment by mpnkhan** [comment]
Different endpoints, but API would return only error. Also could you check what's the  engine. Should be htmlcs by default. 
Post the results here. Will debug
