### ISSUE TITLE
No results on  headless Ubuntu 16.04

### ISSUE THREAD

**Issue by exhannibal** [paypal/AATT#16]
I did a test install on a Ubuntu Gnome 16.04  VM and all worked fine

Now the same install on a headless Ubuntu 16.04 server looked to be working well but now with any test, the loading overlay pops up then disappears and no results are displayed.

Output from AATT
  AATT:log Express started on port  3000 +0ms
  AATT:log E N G I N E  htmlcs +11s
  AATT:log  +15ms
  AATT:log E N G I N E  chrome +3s
  AATT:log  +4ms
  AATT:log E N G I N E  chrome +4s
  AATT:log  +3ms
  AATT:log E N G I N E  chrome +4s
  AATT:log  +3ms
  AATT:log E N G I N E  axe +6s
  AATT:log  +4ms

**Comment by philipf50** [comment]
I am having the exact same issue. No results at all. Fresh install of the latest ubuntu server (headless). Would be nice to get an update on this. Looks like there has been silence on this for almost a year now. I am installing ubuntu-desktop now to see if I can get it working.

**Comment by rajshrimohanks** [comment]
Same issue here. Doesn't work on Ubuntu server as well as in a Ubuntu docker container. Works in Ubuntu desktop as well as in Linux Mint desktop.

**Comment by rajshrimohanks** [comment]
I think I got it fixed. This is due to `libfontconfig` package missing from headless servers/containers which is a dependency for `phantomjs` (which AATT uses). You should install it manually using
```bash
sudo apt-get install libfontconfig
```
