### ISSUE TITLE
Using AATT with a webpage that had no tables

### ISSUE THREAD

**Issue by alexinalexandria** [paypal/AATT#17]
Hello. 

In using the tool in its default form, I have run into an issue when evaluating webpages using the "Section508" level.

If I submit a simple webpage using Source as shown below,, HTML code as shown, AATT endpoint evaluate never responds:

_\<html\>  \<head\> \<body\>\</body\> \</html\>_

However, if a table is added to the body (as shown), I do get a response:

_\<html\>  \<head\> \<body\>\<table\>\</table\>\</body\> \</html\>_

Is there a reason I'm not getting a response for the HTML that has a lack of a table? If I change level to something else (like WCAG2AA), the call works. Why is this? 

Parameters being used (from body in postman)
source: (what is shown above)
engine and output: htmlcs
errLevel: 1,2,3 (although I have also tried 1)
level: Section508
(from Headers in postman)
Content-Type: application/x-www-form-urlencoded
engine: htmlcs

**Comment by mpnkhan** [comment]
Hi @alexinalexandria ,
The evaluation as nothing to do with tables. The section 508 is based on htmlcodesniffer engine. You can past the same html in http://squizlabs.github.io/HTML_CodeSniffer/ and check.
