### ISSUE TITLE
Getting a deprecation warning when using AATT API for accessibility evaluation

### ISSUE THREAD

**Issue by nehasaha** [paypal/AATT#18]
Getting (node:1496) DeprecationWarning: Calling an asynchronous function without callback is deprecated, when using AATT API for accessibility evaluation. I am using node v7.4.0.

**Comment by nanthakumarv** [comment]
Hi @nehasaha ,

I am new to this testing, can you please help me with this.

I used the below code in the config file:
{
  "driver": {
    "browser": "firefox"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "path:../",
      "arguments": ["http://127.0.0.1:8081/evaluate"]
    },
    "view": {
      "module": "nemo-view"
    }    
  }
}

And the below error is being thrown in gitbash
$ node example/usingNemoAccessibility.js
Nemo initialized successfully

C:\Users\391533\nemo-accessibility\node_modules\selenium-webdriver\lib\goog\asyn
c\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
 Error is null Response code is 400

Can you please help with implementing this?

Thanks,
Vithushini

**Comment by mpnkhan** [comment]
Fixed.
