### ISSUE TITLE
How to start using AATT?

### ISSUE THREAD

**Issue by jitendra82** [paypal/AATT#22]
Actually i have installed Node js and git utility, what is next action for start testing?

**Comment by mpnkhan** [comment]
$ git clone https://github.com/paypal/AATT.git
$ cd AATT
##Building and Running
$ sudo npm install
$ git submodule init
$ git submodule update
$ DEBUG=AATT* http_port=3000 node app.js
localhost:3000 should work.

**Comment by RBroden** [comment]
I am running on Windows and get an error with DEBUG=AATT* http_port=3000 node app.js
I have Node and Git installed. I'm setting up a Linux VM now to see if I will have any better luck.
Does this work in Windows?

**Comment by MBeshai** [comment]
Incase anyone else comes across this issue:

You have to set the enviremental variables first so use:

>Set DEBUG=AATT* http_port=3000 node app.js

Then run the command again:

>DEBUG=AATT* http_port=3000 node app.js
