### ISSUE TITLE
Error: Receive E2BIG(argument too long) error when using evaluate API 

### ISSUE THREAD

**Issue by shadowgamefly** [paypal/AATT#23]
Hi,
I am using evaluate end for automate testing. While a dozens of other pages like google, etc works. All our pages received the error likes below. It seems to be a AATT error, but I was unable to catch it in the app.js.

Thanks

Error: spawn E2BIG<br> &nbsp; &nbsp;at exports._errnoException (util.js:1026:11)<br> &nbsp; &nbsp;at ChildProcess.spawn (internal/child_process.js:317:11)<br> &nbsp; &nbsp;at exports.spawn (child_process.js:471:9)<br> &nbsp; &nbsp;at Object.exports.execFile (child_process.js:190:15)<br> &nbsp; &nbsp;at /AATT/app.js:220:17<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/AATT/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/AATT/node_modules/express/lib/router/route.js: 100:13)<br> &nbsp; &nbsp;at Route.dispatch (/AATT/node_modules/express/lib/router/route.js:81:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/AATT/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at /AATT/node_modules/express/lib/router/index.js:233:24

**Comment by mpnkhan** [comment]
what version of phantoms and node are you using ? What os? Do you have any public page url where it fails?

**Comment by shadowgamefly** [comment]
I think I am using the latest official node image (tag:latest) along with the new headless chrome attached to Chrome 59. It seems that those short front page works, but those like cnn.com longer ones will fail.
