### ISSUE TITLE
UI shows 10 issues whereas API returns only 2

### ISSUE THREAD

**Issue by mustufa84** [paypal/AATT#34]
I am trying to research on this tool and I am facing an issue where running the htmlcs through the UI shows me 7 errors but when I use the API and pass the same html code, it only shows me 2 errors

below is my html

<html>
<head>
<script type="text/javascript">
function updateProfile(){
    var xmlhttp = new XMLHttpRequest();
	xmlhttp.open("POST","http://localhost:3000/evaluate", true);
	xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	var generatedSource = new XMLSerializer().serializeToString(this.document);
	xmlhttp.send("source=" + generatedSource + "&output="+"json");
}
</script>
</head>
<body>
    <form>
    <label>First Name;</label><br />
    <input type='text' name='firstName' />
     
    <label>Last Name;</label><br />
    <input type='text' name='lastName' />
     
    <label>Email</label><br />
    <input type='text' name='email' />
    <input type='submit' onClick='updateProfile()' />
    </form>
</body>
</html>

What am I doing wrong?

**Comment by mpnkhan** [comment]
Could you give details of how you are testing? Are you using it part of Automation test case? or are you testing it with UI -> TestHTML?  Note that testhtml will default to WCAG2AA and default will return notices and warnings. 

You can also test the api with http://localhost:3000/test/PAETAPI.html. 

Now nemo accessibility plugin is independent of AATT, so you can test easily with nemo accessibility plugin as well.

**Comment by jaredlevi** [comment]
I'm also having this issue, the UI returns 24 errors while the API is only returning 2.

**Comment by mpnkhan** [comment]
The results are because of the errors/ warning/notices returned in UI. The default engine used etc.  API returns only error by default. 
Kindly let us know what's the engine you use in UI and ruleset selected.

**Comment by andrew041** [comment]
I am seeing this issue as well. From as far as I could tell, all of the settings were the same. Using htmlcs, showing errors, warnings, and notices (1,2,3 in the api), output type of json, and I was hitting the same website both with the UI and API. I tried axe and chrome with the API and only got 'undefined' as a response.
