### ISSUE TITLE
Page keeps loading, doesn't return any result

### ISSUE THREAD

**Issue by ayaz915** [paypal/AATT#35]
Hi,
We have installed AATT in our local,  when we try to test a URL. It doesn't return any result it keeps showing loading.
Please Help.

![image](https://user-images.githubusercontent.com/8925620/36096371-1d5aa626-101c-11e8-8342-fcd7eacffc87.png)

**Comment by namvjsai** [comment]
I've tried the windows branch of the Repo. in Windows 10 and master branch on Ubuntu v1604 instance. UI didn't work on either of the instances.
However, /AATT_API work fine either way.
Please let me know if I need to tweak anything in order it to work.
