### ISSUE TITLE
dockerize AATT

### ISSUE THREAD

**Issue by pgsung** [paypal/AATT#37]
I've successfully dockerized the AATT with Docckerfile

> FROM node:8.9.4
>
>RUN apt-get update && \
>	apt-get install -y openssh-client git && \
>	rm -rf /var/lib/apt/lists/*
>COPY . /usr/src/app
>WORKDIR /usr/src/app
>
>RUN npm install
>RUN git submodule init
>RUN git submodule update
>
>EXPOSE 3000
>ENTRYPOINT DEBUG=AATT* http_port=3000 node app.js

and .dockerignore
>Dockerfile
>./node_modules

It would be nice if the maintainer can include these files into master tree to help people deploying AATT much easier.

**Comment by mpnkhan** [comment]
Please raise a pull request. Would be glad to integrate your changes.
