### ISSUE TITLE
Use as node module

### ISSUE THREAD

**Issue by samboylett** [paypal/AATT#45]
Hi, I've been using AATT via the web API, it is very useful! I think it would be great if you could also use this as a standard node module instead, e.g.:

```javascript
import { evaluate } from '@paypal/aatt';

evaluate({ source: '<html />', output: 'json' }).then(results => {
  console.log(results);
});
```

Is this on the road map? I'm happy to put in a PR for this if not

**Comment by mpnkhan** [comment]
No @samboylett . There is no such thing for now. What's on roadmap is to have a dashboard.  
Please raise a PR.

**Comment by derhecht** [comment]
Could you then just remove the mentioned option in central Readme file? "How to use as a node module"

**Comment by samboylett** [comment]
@derhecht that was a part of this PR

**Comment by derhecht** [comment]
ok, got the problem. when fetching via npm install I will receive an old version where the described things does not work. will try via git pull as described which is never the less quite ugly in npm circumstances.

**Comment by samboylett** [comment]
Yep, I'm currently importing it as:

```
"aatt": "git+https://git@github.com/paypal/AATT.git#98699dd3c1ceded0c752a037af8d881e1d47bcc7"
```

**Comment by mpnkhan** [comment]
@derhecht  Pushed aatt@0.1.1 .  Apologies for the delay..
