### ISSUE TITLE
 Starting revision revision #031d856, ERROR: Unable to load the address!  when evaluate HTML page content

### ISSUE THREAD

**Issue by gnigats** [paypal/AATT#47]
starting at **revision 031d856 Various fixes for being module based rather than running in same folder**

when test from http://localhost:3000/test/AATT_API.html
OR posting with python
requests.post('http://localhost:3000/evaluate', stream=True, verify=False, json={"source": htmlC1})

I got error:  Unable to load the address!
Is there anything I have to do differently ??  thanks !!

**Comment by mpnkhan** [comment]
Try aatt-windows 
https://github.com/mpnkhan/aatt-windows
