### ISSUE TITLE
java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by snehalharde** [paypal/AATT#49]
I get the mentioned error.
The selenium test runs for a long time about 5  mins and then it returns.
java.net.SocketException: Unexpected end of file from server.
Also the terminal log shows the ENGINE statement twice.
Can you please look into it and lmk what I am missing?

code:
String request = "http://localhost:3000/evaluate";
String source = URLEncoder.encode(driver().findElement(By.cssSelector(".formPanel")).getAttribute("outerHTML"), "UTF-8");
  String urlParameters = "source=" + source + "&engine=axe&output=html&errLevel=1,2,3&level=WCAG2AA";

**Comment by mpnkhan** [comment]
Try it now. Had pushed in some fixes.

**Comment by mpnkhan** [comment]
you may also need to do npm install after gitpull as the phantomjs is deprecated for phantomjs-prebuilt (https://github.com/Medium/phantomjs)

**Comment by snehalharde** [comment]
I still get same error.
2 .html files get generated in the tmp folder in a gap of 2 minutes. These
files have the div element from the dom.

**Comment by mpnkhan** [comment]
Please check if your API is working with http://localhost:3000/evaluate

**Comment by snehalharde** [comment]
I get connection refused

**Comment by snehalharde** [comment]
Sorry my bad. I get below
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /evaluate</pre>
</body>
</html>

**Comment by snehalharde** [comment]
I am able to get response from sniffhtml but evaluate do not work. Please
advise

**Comment by mpnkhan** [comment]
I'm sorry you are having trouble. 
I just created a fresh clone and tested everything. I suspect something do with your phantomjs-prebuilt.  Could you kindly create some folder and repeat the steps below? Also paste what you see in logs.

$ git clone https://github.com/paypal/AATT.git
$ npm install
Start in Debug mode
$ DEBUG=AATT* http_port=3000 node app.js
http://localhost:3000/test/AATT_API.html , type axe in input field  'engine'  and submit. 

Please paste what you see in logs.

**Comment by snehalharde** [comment]
Below are the logs

  AATT:log E N G I N E  axe C:\Paypa
A11Y\AATT\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe [
'--config=C:\\Users\\snehal_harde\\VisualregressionDump\\Paypa
A11Y\\AATT\\config\\config.json',
  'C:\\Paypa A11Y\\AATT\\src\\axe_url.js',
  'C:\\Paypa A11Y\\AATT\\tmp\\1562855315860.html',
 'string' ] +42s
  AATT:log E N G I N E  axe C:\Paypa
A11Y\AATT\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe [
'--config=C:\\Users\\snehal_harde\\VisualregressionDump\\Paypa
A11Y\\AATT\\config\\config.json',
  'C:\\Paypa A11Y\\AATT\\src\\axe_url.js',
  'C:\\Paypa A11Y\\AATT\\tmp\\1562855435867.html',
  'string' ] +2m

**Comment by mpnkhan** [comment]
You are using a windows machine. I will test it on windows machine and let you know. 
FYI. The first log takes me 8s for you it takes +42s and +2m and its timing out. Why is it posted twice? are you trying with the above test url only?

**Comment by snehalharde** [comment]
I followed the steps you provided on Jul 11, 2019 at 12:47 AM.
for both axe and chrome the request is triggered twice.

**Comment by snehalharde** [comment]
Do you have any update on this?

**Comment by mpnkhan** [comment]
Created a new branch for windows and tested it on my Windows 10. Hope this works for you. 

```sh
$ git clone https://github.com/paypal/AATT.git
$ cd AATT
$ git checkout windows
$ npm i
$ DEBUG=AATT* http_port=3000 node app.js
```
And test it with http://localhost:3000/test/AATT_API.html.

**Comment by mpnkhan** [comment]
@snehalharde working?
https://github.com/mpnkhan/aatt-windows

**Comment by snehalharde** [comment]
Sorry, I did not get chance to respond.
I do not get error anymore.
I appreciate all your help.

**Comment by mpnkhan** [comment]
You are welcome!
