### ISSUE TITLE
label:question when can we start testing w.r.t. WCAG2.1 using AATT

### ISSUE THREAD

**Issue by vnamani** [paypal/AATT#51]
After reading through the AATT [ReadMe](https://github.com/paypal/AATT/blob/master/README.md).md it looks like the tool supports just the WCAG2.0 and WCAG2.1 hasn't been mentioned in it. So, can I consider AATT doesn't support WCAG2.1. If so, is there any plan for upgrading the libraries?

Q2. I've tried out the AATT integration API and it returned success status. The API consumes just the HTML content for the `source` parameter and not CSS. my question is: isn't it supposed to validate both HTML and CSS in order to test with the WC guidelines?

Thank you

**Comment by namvjsai** [comment]
Thank you for the quick response @mpnkhan, 
We are getting started using this tool but the requirement was basically to test with WCAG2.1 rules, which is what kind of unknown element us currently.
