### ISSUE TITLE
How to use AATT with my own node.js/selenium based framework or with webdriver.io 

### ISSUE THREAD

**Issue by amiya-pattnaik** [paypal/AATT#53]
Hi Team,
I saw this tool and I am impressed on this. Just few questions

1. How can I integrate this tool with my own node.js/selenium based framework (which used Jasmine or Mocha)
2. Can I use this tool with webdriver.io ?
3. Where can I provide the URL to start the testing etc.  And also does it require always navigate to the specific page through selenium scripts. I saw some commands like nomo.drover.url() commands etc.

Thanks in advance.

**Comment by mpnkhan** [comment]
AATT will serve a API within your environment to evaluate. You need to use the API end point "https://your_nodejs_accessibility_server/evaluate" . 

Example with webdrver.io

//scan
function scan(source) {
    if (browser.sessionId){
    	    console.log('S O U R C E', source);
			var body = {
			  'source': '<input>',
			  'engine' : 'axe',
			  'output': 'json'
			},
			options = {
			  'headers': {
			    'Content-Type': 'application/json'
			  },
			  'url': 'http://localhost:3000/evaluate',
			  'method': 'POST',
			  'body': body,
			  'json': true,
			  'rejectUnauthorized': false
			};

                return new Promise(function(resolve, reject) {
                    let retStr ='';                    
					request(options, function (err, response, responseBody) {
						if (err) {
							reject(err);
						}
						if (err || response.statusCode !== 200) {
						  reject('Error is ' + err + ' Response code is ' + (response && response.statusCode));
						}
			            else{
                            // retStr = processResultsAxe(responseBody);
                            retStr = responseBody;
                            resolve(retStr);
			            }				
					});

                }) //Promise			

    }
    else{
        reject('Session Id was not defined');
    }
}

Yes you need to navigate.

**Comment by amiya-pattnaik** [comment]
Thanks Nawaz for the updates.
Just help me with below silly question.

1. API endpoint "https://your_nodejs_accessibility_server/evaluate" . What does it mean? Do you mean that the actual endpoint of my application? for example, if I am testing the login functionality of my application then should I give the login endpoint URL here ?

2. 'url': 'http://localhost:3000/evaluate'  in Options. What id does and what is its signifiance?

Please advise. Thanks in advance.
Amiya

**Comment by mpnkhan** [comment]
1. API end point is http://localhost:3000/evaluate. That is machine where your AATT runs. 
You could also install aatt as node module and use it, see readme. 
2. Options also defined in Readme. you can choose engine, some engine specific parameters. 
3. source should be page source which want to test
4. Just call evaluate or scan method(shown above) in you test case where you thing your html source is ready for testing.

**Comment by amiya-pattnaik** [comment]
Thanks, Nawaz for the updates.
Few questions again.
1. in the above example i.e. function scan(source), the in parameter `source` is never being used
2. I could not find any call to the   AATT module?  Should we import the AATT module in the test?
3. Inside the scan() function it uses the request module. Should we also import the request module?
4. how `http://localhost:3000/evaluate` will start? . Will it be automatically be taken care ?

Please advise. I appreciate your help.
Thanks
